name: PlantMate
options:
  bundleIdPrefix: com.plantmate
  deploymentTarget:
    iOS: 17.0
  developmentLanguage: ko
  createIntermediateGroups: true

settings:
  base:
    PRODUCT_NAME: PlantMate
    TARGETED_DEVICE_FAMILY: 1,2
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 17.0

targets:
  PlantMate:
    type: application
    platform: iOS
    sources:
      - path: PlantMate
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.plantmate.PlantMate
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
        ENABLE_PREVIEWS: true
        DEVELOPMENT_ASSET_PATHS: "PlantMate/Preview\\ Content"
